### PR TITLE
Properly handle unicode length

### LINKED ISSUE #15: Multibyte characters (emoji) are considered multiple characters
for the ContentState:

```{
  "blocks": [
    {
      "data": {},
      "depth": 0,
      "entityRanges": [
        {
          "key": 0,
          "length": 12,
          "offset": 0
        }
      ],
      "inlineStyleRanges": [],
      "key": "471ua",
      "text": "be a fish 🐡~",
      "type": "header-one"
    }
  ],
  "entityMap": {
    "0": {
      "data": {
        "data": {
          "color": "#ffffff"
        }
      },
      "mutability": "MUTABLE",
      "type": "ENTITY"
    }
  }
}```

the entity "ENTITY with `{ data: { color: "#ffffff" } }` is only applied to the emoji, missing the trailing "~" character. Removing the trailing "~" character splits the multibyte emoji into halves (half white, half default color). 

`> "be a fish 🐡~".length // = 13`, but is really 12 multibyte characters. The fix would be to treat multibyte characters as single characters, which would mean manually implementing multibyte functions for calclulating length and assessing offsets. ([similar to this](http://stackoverflow.com/questions/2848462/count-bytes-in-textarea-using-javascript))

### PR DESCRIPTION
**Pull request by lokiuz**
This should fix #15 , adds a single dependency and also needs real tests before merging.

### CODE REVIEW

**Comment by grrowl** [comment]
Works great in our initial testing — placing emojis before inline entities used to mis-place the inline entity and subsequent ranges, but does not on this branch.

**Comment by grrowl** [comment]
Only a little worried about performance of punycode in this way ([although they're mindful of it](https://github.com/bestiejs/punycode.js/issues/49)) but it's looking good so far, and easy enough to optimise later if need be :)

**Comment by lokiuz** [comment]
Yeah bit worried about performance myself.

Form what I understand and tested so far it should be possible to drop punycode ucs2.decode in favor of `Array.from` and then just join('') instead of encode. 

I'm gonna write some more test for this and then pick the method with better performance.

**Comment by lokiuz** [comment]
Added some test and ran some pref checks against both versions. While punycode seems marginally faster on node, in chrome 53 results were almost same. So far i think it would be better to stick with Array.from as that's a native solution.

**Comment by jalieven** [comment]
For references sake. Also see #27

**Pull request merged**
